export default Object.freeze({
  ACCOUNT: "Account",
  ACTIVATION: "Activation",
  CASES: "Cases",
  CASE_DETAILS: "CaseDetails",
  CHANGE_EMAIL: "ChangeEmail",
  CHANGE_PASSWORD: "ChangePassword",
  CHANGE_PHONE: "ChangePhone",
  FORGOT_PASSWORD: "ForgotPassword",
  HOME: "Home",
  LOGIN: "Login",
  NEW_CASE: "NewCase",
  OTP_VERIFICATION: "OtpVerification",
  REGISTER: "Register",
  RESET_PASSWORD: "ResetPassword",
  WELCOME: "Welcome",
});
